env:
  browser: true
  es6: true
  jquery: true
  webextensions: true

extends:
- eslint:recommended
- airbnb-base
- plugin:react/recommended

parserOptions:
  ecmaVersion: 6

root: true

rules:
  arrow-parens: off
  comma-dangle: off
  function-paren-newline: off
  guard-for-in: off
  import/no-named-as-default: off
  import/prefer-default-export: off
  no-multi-assign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-use-before-define: off
  object-curly-newline: off
  react/prop-types: off
